name: Update Codeforces Rating

on:
  schedule:
    - cron: "0 0 * * 0" # This runs the script every Sunday at midnight UTC
  workflow_dispatch: # Allows you to manually trigger the workflow from GitHub

jobs:
  update-rating:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Adjust the Python version as needed

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml  # Add any other dependencies here

      - name: Run update script
        run: python fetch_codeforces_rating.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add _data/codeforces_rating.yml
          git commit -m "Update Codeforces rating"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
